### PR TITLE
Add python 3.6 support.

### PR DESCRIPTION
**Pull request by jrocketfingers**
Covers #305.

Sidenote: There are some errors with DRF 3.0 across all python versions in my environment, has anyone had that happen?

### CODE REVIEW

**Comment by jrocketfingers** [comment]
Ooook, so there's a problem with travis, you can either have a 3.5 or a 3.6 environment. But then again I didn't work with it extensively.

The good news is that the tests pass with 3.6, but please don't merge until we figure out how to set up travis (I'll check DRF again).

**Comment by carltongibson** [comment]
This was the DRF PR that added Python 3.6: https://github.com/tomchristie/django-rest-framework/pull/4811 — you basically have to specifically `include` the extra environments. 

Personally I don't like this: you end up duplicating the `tox` config in the travis config, so every time you make a change you need to make it in both places. 

For https://github.com/carltongibson/django-filter/pull/631 I'm looking at using docker with the required Python versions pre-installed so I can just use tox (as we have been doing until hitting this problem). It's a little bit slower currently, because the caching needs tweaking, but it works. You might want to look at it.

**Comment by jheld** [comment]
Any updates here?

**Comment by jrocketfingers** [comment]
Been way to far from this recently. Won't have time to dive back in for a couple of weeks, feel free to take over.

**Comment by blueyed** [comment]
For reference, tox-travis might be an option: https://github.com/carltongibson/django-filter/pull/651/files.

**Comment by blueyed** [comment]
Thanks, continued in https://github.com/GetBlimp/django-rest-framework-jwt/pull/371.

**Pull request closed without merging**
