### PR TITLE
Private/public keys

### LINKED ISSUE #136: Add support for using public/private keys
The default JWT_DECODE_HANDLER/JWT_ENCODE_HANDLER blindly use the JWT_SECRET_KEY. However, and quite annoyingly, if you are using public/private keys to handle the verification then you need to pass the private key in the encode_handler, and the public one in the decode_handler.

The quickest way to fix this is to modify jwt_decode_handler like so:

```
def jwt_decode_handler(token):
    options = {
        'verify_exp': api_settings.JWT_VERIFY_EXPIRATION,
    }

    key = api_settings.JWT_SECRET_KEY
    if hasattr(key, "public_key"):
        key = key.public_key()

    return jwt.decode(
        token,
        key...
```

But obviously that's not super clean, although I think it's somewhat elegant and does fix the issue. Any thoughts?

### PR DESCRIPTION
**Pull request by willseward**
Replaces #144.
Closes #136.

Adds support for public and private key pairs.

### CODE REVIEW

**Comment by willseward** [comment]
Hi, we are looking to implement this fairly soon. What is the likelihood that this (or another solution) can be merged soon?

**Comment by jpadilla** [comment]
@willseward looks good. I'd love a simple test mostly to demonstrate usage. It'd also be helpful to document what would happen if a symmetric algo is set, say we left the default, but added public/private keys.

**Comment by willseward** [comment]
No problem, I'll write up some tests. 

Good point about the symmetric algo. Do you think validating the settings would be sufficient?

**Comment by jpadilla** [comment]
@willseward Not sure if there's anything to do really, let's see if the underlying PyJWT library raises something useful in that case.

**Comment by willseward** [comment]
Looks like it throws a `TypeError: Expecting a string- or bytes-formatted key.` I'll put that in the docs.

**Comment by willseward** [comment]
Travis is failing because of a freezegun issue. I had to upgrade the library for it to run on 2.7, but it evidently doesn't like 3.3 or 3.4. I'm happy to revert that dep upgrade; I just need to ask if you have run into this before.

**Comment by willseward** [comment]
It appears that cffi from the crypto lib is interfering with freezegun. Any opposition to restructuring the tests to run the RSA tests last and without freezegun? I'll be sure to document why.

**Comment by willseward** [comment]
Tests are passing. How does that look to you?

**Comment by vovanbo** [comment]
What about merging it into master branch? I've done it in my fork and it works perfectly.

**Comment by carltongibson** [comment]
@willseward Any chance you could update this to the latest `master`? Thanks!

**Comment by willseward** [comment]
It's not my call.

@jpadilla How does that sounds to you?

**Comment by jpadilla** [comment]
@willseward @carltongibson let's move forward with this. thanks!

**Comment by carltongibson** [comment]
@willseward We can't merge it unless it's updated. (There are conflicts, probably small)

**Comment by vovanbo** [comment]
I saw conflicts only in `tox.ini` file.

**Comment by willseward** [comment]
Oh, sorry @carltongibson, I misread your comment. I'll rebase to master

**Comment by carltongibson** [comment]
@willseward Nice addition. Great work. Thanks!

**Comment by SagiMedina** [comment]
Hi,
I'm still getting this error:
TypeError('Expecting a string- or bytes-formatted key.')

**Comment by SagiMedina** [comment]
T

**Comment by willseward** [comment]
@SagiMedina Can you post the relevant section of your `settings.py`?

**Comment by vovanbo** [comment]
@SagiMedina do you use package from `master` branch? Public/private keys support is not released in PyPi yet.

**Comment by SagiMedina** [comment]
Sorry, My key var was not saved properly the postactivate file

**Comment by vovanbo** [comment]
When it will be released on PyPi? Milestone for 1.9 is not contain any another issues for this moment.

**Pull request merged**
