### PR TITLE
Long running refresh tokens

### PR DESCRIPTION
**Pull request by ticosax**
this is an attempt to resume work started in #94

@fxdgear It is mostly your work here.

### CODE REVIEW

**Comment by ticosax** [comment]
needs #118 to be merged first.
Then I'll rebase it.

**Comment by fxdgear** [comment]
@ticosax thanks for taking this over. I got really busy with work and haven't had a chance to pick this back up.

**Comment by ticosax** [comment]
@fxdgear thank you for the implementation ! :smile:

**Comment by ticosax** [comment]
@fxdgear please tell can you tell me what is the reasoning behind the unicity of app field.

```python
class RefreshToken(models.Model):
   app = models.CharField(max_length=255, unique=True)
```
I think it should be:

```python
class RefreshToken(models.Model):
    class Meta:
        unique_together = ('user', 'app')
```
instead.

**Comment by fxdgear** [comment]
@ticosax oh you're right. It should be `unique_together`

**Comment by ticosax** [comment]
@fxdgear Thank you for your answer. I  updated the PR to reflect the change

**Comment by fxdgear** [comment]
:+1:

**Comment by ticosax** [comment]
I will rebase now #118 is merged

**Comment by ticosax** [comment]
will come back in a better shape

**Pull request closed without merging**
