### PR TITLE
Allow subclassing JSONWebTokenAuthentication

### PR DESCRIPTION
**Pull request by cancan101**
Right now `JSONWebTokenAuthentication` assumes that the jwt will come in the header. The JWT does not require this (see [Making a service Call](https://developer.atlassian.com/static/connect/docs/concepts/authentication.html)). The jwt may come in the querystring. The ability to send the jwt in the querystring is needed in cases where the user cannot set the header (for example the src element in HTML).

This refactoring make it easy to change the source for the JWT. For example:
```python
class JSONWebTokenAuthenticationCreateQS(JSONWebTokenAuthenticationBase):
    def get_jwt_value(self, request): 
         return request.QUERY_PARAMS.get('jwt')
```

### CODE REVIEW

**Comment by cancan101** [comment]
An alternative to the way I set it up with `JSONWebTokenAuthentication` extending `JSONWebTokenAuthenticationBase` would be to use a mixin and have three classes: `JSONWebTokenAuthenticationBase`, `JSONWebTokenAuthentication`, `JSONWebTokenFromHeader`.

**Comment by jpadilla** [comment]
@cancan101 yeah these seems ok. It perhaps might be a good idea to add something about this to the docs, perhaps with that `JSONWebTokenAuthenticationCreateQS ` example you gave up top.

**Comment by cancan101** [comment]
Are you okay with the name of the base class: `JSONWebTokenAuthenticationBase`?

**Comment by jpadilla** [comment]
@cancan101 hmmm how about `BaseJSONWebTokenAuthentication` like DRF's `BaseAuthentication`.

**Comment by cancan101** [comment]
docs and rename done.

**Comment by cancan101** [comment]
bump

**Comment by jpadilla** [comment]
@cancan101  looks great, thanks again!

**Pull request merged**
