### PR TITLE
Update supported versions in README and index.

### PR DESCRIPTION
**Pull request by mblayman**
This update brings the documentation up-to-date with what the Travis
test matrix supports. I didn't drop Django 1.6 from the list in case
it was there for historical reasons.

### CODE REVIEW

**Comment by carltongibson** [comment]
I'm all for this. I'd say you can be bolder, dropping support for Django 1.6 and 1.7 — and remove those from travis. 

What about DRF 2.x? Anyone still on that can stick to the existing version of JWT. Discuss.

After that it's just ripping out the unneeded stuff from compat.

@mblayman: are you up for adding those further changes?

**Comment by mblayman** [comment]
Sure, it's be happy to make changes. Anything that helps get:

```
-e git+https://github.com/GetBlimp/django-rest-framework-jwt@master#egg=djangorestframework_jwt
```
out of my `requirements.txt` file is good news for me.

I agree with dropping Django 1.6 and 1.7 since they are no longer supported by the Django project itself. I'm fairly new to DRF so I can't really speak to dropping DRF 2.X or not.

**Comment by carltongibson** [comment]
@jpadilla What say you sir? 

Shhhh... I think [he already said yes to this](https://github.com/GetBlimp/django-rest-framework-jwt/issues/216#issuecomment-194245923) 🙄

**Comment by jpadilla** [comment]
Yeah, I'm all for dropping Django 1.6 and 1.7 as well as dropping DRF 2.X.

@mblayman @carltongibson thank you!

yeah

**Comment by mblayman** [comment]
I think this PR is ready for review now. I cleaned out the `tox.ini` and `.travis.yml`, removed the unneeded stuff from `compat.py`, and updated the documentation to drop references to Django 1.6, Django 1.7, and DRF 2.4.

**Comment by auvipy** [comment]
looks good to me. but should drf 3.0 and 3.1 needed to be supported ?or should be kept for some time more?

**Comment by mblayman** [comment]
Did I make a mistake? The only 3.0 and 3.1 stuff that I removed in the test matrix was when it overlapped with Django 1.6 or Django 1.7.

**Comment by carltongibson** [comment]
Good work! Thanks!

**Pull request merged**
