### PR TITLE
Fix tests: bump cryptography and use include matrix

### PR DESCRIPTION
**Pull request by blueyed**
This fixes the tests.

### CODE REVIEW

**Comment by jpadilla** [comment]
@blueyed thank you so much for getting to this! How do you feel about write access to repo? Always welcome as a collaborator 😃

**Comment by blueyed** [comment]
@jpadilla 
Sure.. :)

**Comment by blueyed** [comment]
@jpadilla 
Thanks!
btw: I do not have permissions to restart Travis jobs - maybe you should create / use an organisation to handle this across different services?!

**Comment by jpadilla** [comment]
@blueyed thank you dude! Check on the Travis thing now. Will update in a bit.

**Comment by blueyed** [comment]
@jpadilla 
Thanks, I could restart https://travis-ci.org/GetBlimp/django-rest-framework-jwt/jobs/275972482.

**Pull request merged**
