### PR TITLE
Added the ability to use custom renderers for the JWT endpoints.

### PR DESCRIPTION
**Pull request by Jwpe**
Ran into a use-case today where I wanted to modify the format of the error response from a failed login attempt. I've already written a DRF custom renderer to neatly wrap my responses and errors, and I thought it would be cool if I could apply this renderer to the JWT endpoints as well. 

As far as I can tell it's an extremely simple change! Would definitely appreciate thoughts and feedback though.

### CODE REVIEW

**Comment by Jwpe** [comment]
@jpadilla does this seem like something you'd want to add?

**Comment by jpadilla** [comment]
@Jwpe wouldn't just setting `DEFAULT_RENDERER_CLASSES` work? You can also do something like:

```python
urlpatterns = [
    url(r'^api-token-auth/', ObtainJSONWebToken.as_view(renderer_classes=[CustomRenderer]),
]
```

**Comment by Jwpe** [comment]
@jpadilla the first suggestion wouldn't work, unfortunately, because the `render_classes` on the base view is hard-coded as `+        'rest_framework.renderers.JSONRenderer`. It could be made to work if that was changed just to use DRF's `DEFAULT_RENDERER_CLASSES` - might be preferable to a specific setting just for this.

The second way does work, but in my mind it's less elegant than permitting a global setting. It requires importing the view and the custom renderer into your URLs.

Maybe a good middle ground would just be changing the base class to have:
```python
from rest_framework.settings import api_settings as drf_api_settings
...

class JSONWebTokenAPIView(APIView):
...
renderer_classes =  drf_api_settings.DEFAULT_RENDERER_CLASSES
```

**Comment by jpadilla** [comment]
@Jwpe I'm thinking `parser_classes` and `renderer_classes` are better off removed. It'll just default to whatever you set on your DRF settings. Thoughts?

**Comment by Jwpe** [comment]
@jpadilla that totally works. It would be a lot simpler. If you like I can change the PR to reflect that?

**Comment by jpadilla** [comment]
@Jwpe that'd be great, yeah!

**Comment by Jwpe** [comment]
@jpadilla modified this and rebased to take out the irrelevant changes I made before.

**Comment by jpadilla** [comment]
@Jwpe thanks!

**Pull request merged**
