### PR TITLE
Some specialized serializers needs the request in context.

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by jpadilla** [comment]
@ticosax what if instead we did something like what `GenericAPIView` does providing `get_serializer()`, `get_serializer_class()`, and `get_serializer_context()`?

**Comment by ticosax** [comment]
Sounds good. I'll work on it from next Monday.
I'll keep you updated.

**Comment by ticosax** [comment]
@jpadilla 
I almost copy pasted the code from GenericAPIView. and provided `request` and `view` entries in context. May be you prefer I keep it empty like it is today ?

**Comment by jpadilla** [comment]
@ticosax that's fine by me, thanks!

**Pull request merged**
