### PR TITLE
The verify argument is deprecated in jwt.decode

### PR DESCRIPTION
**Pull request by blueyed**
This uses the "verify_signature" option instead.

### CODE REVIEW

**Comment by angvp** [comment]
This PR is breaking the tests, would you mind to fix it?

**Comment by blueyed** [comment]
Sure.

But it looks like `verify` is not actually deprecated for `PyJWT.decode`, but only `PyJWS.decode`.
Let's wait on the outcome of https://github.com/jpadilla/pyjwt/pull/271.

**Comment by jpadilla** [comment]
@blueyed can you still check this out, if not I can take over. Looking to release a new version today.

**Comment by blueyed** [comment]
With https://github.com/jpadilla/pyjwt/pull/271 there are no more deprecation warning here, so this can be closed.

**Comment by jpadilla** [comment]
Ace, thanks!

**Pull request closed without merging**
