### PR TITLE
Added jwt_response_payload_handler which allows returning additional response data

### PR DESCRIPTION
**Pull request by erichonkanen**
Adds the ability to attach additional info besides the "token" to the response for the obtain and refresh endpoints.

### CODE REVIEW

**Comment by erichonkanen** [comment]
@jpadilla lmk if this looks better... I think it would be nice to only have to implement a custom jwt_response_payload_handler()" function like I put in the README example but if you think this should be left to a custom auth APIView let me know...

**Comment by jpadilla** [comment]
Failing test.
> rest_framework_jwt/serializers.py:65:1: W293 blank line contains whitespace

Also, I think I prefer to have anything related to additional response data handled in the views not in the serializer. So basically serializers stay as they were. Makes sense?

**Comment by erichonkanen** [comment]
@jpadilla ah ok gotcha, do you like the idea of being able to attach additional response data w/o having to write a whole custom auth view though? To me it seems nice but maybe I'm biased... I'll move it to the view and check back later..

**Comment by erichonkanen** [comment]
@jpadilla updated per conversation and cleaned up... Only thing that may be missing is any additional tests, if you have any ideas on that let me know otherwise it should be good to go! Thanks for the assistance

**Comment by jpadilla** [comment]
@erichonkanen I think we should have at least one test that shows custom response data in a view. Everything else looks good to me. Great job!

**Comment by erichonkanen** [comment]
@jpadilla So I ran into some trouble bc the project I'm testing with uses a custom user model and it hiccup'd when I ran test.

That said is this the sort of test you wanted? Or something more involved? Also not sure if theres a better way to condense that decorator override_settings()

```
class ObtainJSONWebTokenTests(BaseTestCase):
    @override_settings(JWT_AUTH['JWT_RESPONSE_PAYLOAD_HANDLER']='tests.utils.jwt_response_payload_handler')
    def test_jwt_login_custom_response_json(self):
        """
        Ensure JWT login view using JSON POST works.
        """
        client = APIClient(enforce_csrf_checks=True)

        response = client.post('/auth-token/', self.data, format='json')

        decoded_payload = utils.jwt_decode_handler(response.data['token'])

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(decoded_payload['username'], self.username)
        self.assertEqual(response.data['user'], self.user)
```

**Comment by jpadilla** [comment]
@erichonkanen yeah I think that's the idea.

**Comment by erichonkanen** [comment]
@jpadilla Hey so I pushed up my latest with changes to test to a) fix User model issue, b) include test for custom response. However I can't test this as I'm having issues with testing for some reason.

What are your steps to test this package? I am (in active py3.4 virtualenv) "django-admin test" while in ~/.virtualenvs/project/src/djangorestframework-jwt/"

I am getting operational error saying no CustomUser model (from /tests/models.py).

I can try to resolve this or maybe you can test what I have? LMK.. I probably need to get testing resolved for future reference anyways

**Comment by jpadilla** [comment]
@erichonkanen try running tests with `./runtests.py` instead of `django-admin test`

**Comment by erichonkanen** [comment]
debugging issue that cropped up, the refresh functionality is working but now I'm getting signature has expired.. tricky to track down what's causing this.. seems like the token isn't actually being refreshed

**Pull request merged**
