### PR TITLE
user import problem for custom users issue fixed

### PR DESCRIPTION
**Pull request by cenkbircanoglu**
if custom model used user model import create error like this:
.....
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### CODE REVIEW

**Comment by cenkbircanoglu** [comment]
while starting application it reads first import part which doesnt loaded yet. because we use custom user.
Change in the installed_apps order doesnt fix the problem. If someone know how can pass this error without change import order it will be helpfull

**Comment by jpadilla** [comment]
@cenkbircanoglu was it also necessary to reorder the `from rest_framework_jwt.settings import api_settings`?

**Comment by cenkbircanoglu** [comment]
no it is not necessary i'm using Pycharm and it has "optimize imports" shorcuts and i have a practice(habit) that's all beacuse of it.

**Comment by jpadilla** [comment]
@cenkbircanoglu since it seems you're using a custom user model, can you check this [thread](https://github.com/GetBlimp/django-rest-framework-jwt/issues/36) out. Does this fix whatever might have been going on there?

**Comment by cenkbircanoglu** [comment]
This will fix that problem:
"Well the first problem is when AUTH_USER_MODEL is changed, because there is a problem with the imports. But that is not the main problem, it is easy to fix."

But i dont understand what his problem is exactly.

**Comment by jpadilla** [comment]
@cenkbircanoglu thanks!

**Pull request merged**
