### PR TITLE
Update of django, drf, python version handling in tox.ini

### PR DESCRIPTION
**Pull request by angvp**
- Removed tests for drf 2.4, 3.0 because django versions 1.8,1.9,1.10 doesn't play well with them.
- Untie drf and django to specific releases for a version, and instead get the latest release of every version

Some of these changes were done in #252 but weren't merged because #256 was more complete adding support of drf3.4 and django 1.10, however I rather like to test against the latest release of a version so this is the main motivation of this PR.

Regards.

### CODE REVIEW

**Comment by angvp** [comment]
Closing it because it got no interest from the maintainers.

Note to the maintainers: Please drop some feedback to ALL the PR that you have open, merge, reject them or whatever but give feedback, the standby status is the worst part.

**Comment by jpadilla** [comment]
@angvp definitely interested, just a bit caught up in work. Should be able to catch up with issues and pull requests for this project soon. Thanks for the reminder.

As a note, anyone that wants to step up and help out with maintenance will be greatly welcome.

**Comment by angvp** [comment]
Count me in!

**Comment by jpadilla** [comment]
@angvp awesome, thanks! just sent out an invite. Unfortunately Travis CI is still having issues after AWS outage so I can't see what's failing now here after my resolve. Will wait it out.

**Comment by angvp** [comment]
@jpadilla Can you re run travis on this pr? thanks!

**Comment by jpadilla** [comment]
@angvp green :)

**Comment by jpadilla** [comment]
Just released this under [v1.10](https://github.com/GetBlimp/django-rest-framework-jwt/releases/tag/1.10.0). Thank you @angvp!

**Pull request merged**
